---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/yh/Desktop/KU/25-2/Data_Structure/lec10-13/stack'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003AA8, symSize: 0x118 }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _top, symObjAddr: 0x434, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x6E, offset: 0x6E, size: 0x8, addend: 0x0, symName: _capacity, symObjAddr: 0x43C, symBinAddr: 0x100008008, symSize: 0x0 }
  - { offsetInCU: 0x83, offset: 0x83, size: 0x8, addend: 0x0, symName: _num_copy, symObjAddr: 0xFA8, symBinAddr: 0x100008010, symSize: 0x0 }
  - { offsetInCU: 0x98, offset: 0x98, size: 0x8, addend: 0x0, symName: _count, symObjAddr: 0xFAC, symBinAddr: 0x100008014, symSize: 0x0 }
  - { offsetInCU: 0xB4, offset: 0xB4, size: 0x8, addend: 0x0, symName: _stacks, symBinAddr: 0x100008018, symSize: 0x0 }
  - { offsetInCU: 0xEA, offset: 0xEA, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003AA8, symSize: 0x118 }
  - { offsetInCU: 0x13C, offset: 0x13C, size: 0x8, addend: 0x0, symName: _push, symObjAddr: 0x118, symBinAddr: 0x100003BC0, symSize: 0x98 }
  - { offsetInCU: 0x16E, offset: 0x16E, size: 0x8, addend: 0x0, symName: _stackFull, symObjAddr: 0x1B0, symBinAddr: 0x100003C58, symSize: 0x104 }
  - { offsetInCU: 0x1A0, offset: 0x1A0, size: 0x8, addend: 0x0, symName: _pop, symObjAddr: 0x2B4, symBinAddr: 0x100003D5C, symSize: 0x88 }
  - { offsetInCU: 0x1C8, offset: 0x1C8, size: 0x8, addend: 0x0, symName: _stackEmpty, symObjAddr: 0x33C, symBinAddr: 0x100003DE4, symSize: 0x18 }
  - { offsetInCU: 0x1F0, offset: 0x1F0, size: 0x8, addend: 0x0, symName: _printStack, symObjAddr: 0x354, symBinAddr: 0x100003DFC, symSize: 0xE0 }
...
